### ISSUE TITLE
129 examples in the re_arc.zip dataset are exceeding height of 30 (task e26a3af2.json)

### ISSUE THREAD

**Issue by rebootl** [michaelhodel/re-arc#10]
is_grid should check grid is max. height 30

**Comment by michaelhodel** [comment]
you're right, thanks - fixed. see https://github.com/michaelhodel/re-arc/commit/57ddb494e7a437c0604b1d2558a14e16d8f60f13

**Comment by rebootl** [comment]
this fixes the function, the data that was already generated in the dataset is still wrong though ;)
