### ISSUE TITLE
generate_dataset hang in task 19 at 5%

### ISSUE THREAD

**Issue by neoneye** [michaelhodel/re-arc#2]
# Problem

The program invokes `generate_dataset()` and does nothing else.

I have tried running the program multiple times, and it's the same place it gets stuck.

```bash
michaelhodel-re-arc % python3 -m venv venv
michaelhodel-re-arc % source venv/bin/activate
(venv) michaelhodel-re-arc % pip install -r requirements.txt
(venv) michaelhodel-re-arc % cat export.py 
from main import *
generate_dataset()
(venv) michaelhodel-re-arc % python3 export.py 
task 19/400, example 1000/1000:   5%|█████▋               | 19/400 [01:12<48:17,  7.61s/it]
```

After 10 minutes with no change to progress, I aborted it.

- Pressing Ctrl C and there is no backtrace of what the program is currently doing. 
- It seems like Ctrl C doesn't terminate the process.
- I had to close the tab to kill the process. 

# Environment

```
(venv) michaelhodel-re-arc % python3 --version
Python 3.12.2

(venv) michaelhodel-re-arc % pip freeze
contourpy==1.2.1
cycler==0.12.1
fonttools==4.51.0
kiwisolver==1.4.5
matplotlib==3.8.4
numpy==1.26.4
packaging==24.0
pillow==10.3.0
pyparsing==3.1.2
python-dateutil==2.9.0.post0
six==1.16.0
tqdm==4.66.2

(venv) michaelhodel-re-arc % uname -a
Darwin award.home 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64
```

# Solution

Unfortunately I don't have a backtrace for you. So I have no idea about the solution to fix it.

**Comment by michaelhodel** [comment]
It runs just fine for me.

This is the version of Python / matplotlib / tqdm I am using:

import sys, matplotlib, tqdm
print(sys.version)
print(matplotlib.__version__)
print(tqdm.__version__)

3.9.6 (default, Nov 10 2023, 13:38:27) 
[Clang 15.0.0 (clang-1500.1.0.2.5)]
3.8.2
4.66.1

Do you still get the same issues when you use the these versions?

In general: While I know the generate_dataset can run for 10'000 examples per task without hangs (as I have done so on my machine), there may indeed be the possibility for a generator to hang (depending on the RNG), as some have while loops, i.e. no hangs are not guaranteed - to ensure no hangs I would suggest e.g. using a wrapper / modification to the code using timeouts & restarts.

**Comment by neoneye** [comment]
IMHO: The deeper problem here is that it doesn't work with the newest python version.

It works by downgrading to an older python version using `pyenv` on macOS.

```bash
michaelhodel-re-arc % eval "$(pyenv init -)"
michaelhodel-re-arc % pyenv local 3.9.6  
michaelhodel-re-arc % python3 --version
Python 3.9.6
michaelhodel-re-arc % python3 -m venv venv
michaelhodel-re-arc % source venv/bin/activate
(venv) michaelhodel-re-arc % pip install -r requirements.txt
Successfully installed contourpy-1.2.1 cycler-0.12.1 fonttools-4.51.0 importlib-resources-6.4.0 kiwisolver-1.4.5 matplotlib-3.8.4 numpy-1.26.4 packaging-24.0 pillow-10.3.0 pyparsing-3.1.2 python-dateutil-2.9.0.post0 six-1.16.0 tqdm-4.66.2 zipp-3.18.1
(venv) michaelhodel-re-arc % python3 export.py 
python3 export.py 
task 400/400, example 1000/1000: 100%|█████████████████████████████| 400/400 [38:14<00:00,  5.74s/it]
(venv) michaelhodel-re-arc % 
```
