### ISSUE TITLE
Need documentation of json format - doesn't seem to match ARC

### ISSUE THREAD

**Issue by drawlinson** [michaelhodel/re-arc#4]
Hi, if possible can you explain the json format of the tasks? I've generated a few datasets and explored the contents. They don't seem to contain task grids (2d), only a 1d array of values. 
```
file_path = "./re_arc/re_arc/tasks/017c7c7b.json"
dataset = None
with open(file_path) as f:
    dataset_json = json.load(f)

print(f"# Tasks: {len(dataset_json)}")

task_0 = dataset_json[0]
print(task_0.keys())
inputs = task_0["input"]
output = task_0["output"]
print(inputs[0])
print(output[0])
```
produces:
```
# Tasks: 1000
dict_keys(['input', 'output'])
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0]
```
The ARC json format is:
```
[
  {
     "train": [
        {
            "input": [ [c, c, c], [c, c, c], [c, c, c], ]
            "output": [ [c, c, c], [c, c, c], [c, c, c], ]
        },
        {
            ...
        }
     ],
     "test": [
         ... (same as train)
     ]
  },
  {
     ...
  },
  ...
]
```
... where c is a colour value. `input` and `output` are 2d i.e. arrays of arrays.

From what I can tell the re-arc format is:
```
[
        {
            "input": [c, c, c]
            "output": [c, c, c]
        },
        {
            ...
        }
  ...
]
```
i.e. the top level `train` / `test` grouping is gone (seems reasonable, re-arc can be arbitrarily broken into train/test sets), and additionally the 2d matrices seem to have become 1d. This latter change seems to be a problem.

Both ARC and re-arc seem to have variable length arrays depending on grid or image size, which is fine - but I'm not sure how to interpret the 1d array provided. Presumably the grids aren't always square...

**Comment by michaelhodel** [comment]
While yes, there is no train-test split of examples, the latter should not (and for me is not) the case. re_arc.zip was created by zipping the outputs produced by running the main function (generate_dataset). If I unzip re_arc.zip and open one of the .json files containing examples, I see no 1d lists, but only 2d lists - as expected.

What you are printing is not the number of tasks, but the number of examples. dataset_json[0] gives you the first example, not the first task. task_0["input"] gives you the input of the first example, not multiple inputs. Hence, inputs[0] will show you the first element of input grid of the first example, which is the first row of that grid - a 1d list.

**Comment by drawlinson** [comment]
Ok I see that now, you're right
